---
author: "Vered Chalifa-Caspi"
date: "17.5.2023"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---
# About

This script was taken and modified from DeSeq2 module (https://github.com/bioinfo-core-BGU/neatseq-flow-modules/tree/master/neatseq_flow_modules/Liron/DeSeq2_module)
written by Liron Levin (levinl@bgu.ac.il).
It retrieves annotation from Ensembl for a given organism.

# Load libraries

```{r setup, include=FALSE}

library('AnnotationHub')
library('ensembldb')
library('biomaRt')
library('clusterProfiler')
library("stringr")
library("tibble")
library("dplyr")

```

# Settings

```{r parameters}

opt_Species = "Mus Musculus"
opt_outDir  = "Func_annot_data"

if(!dir.exists(opt_outDir)) dir.create(opt_outDir)

```

# Functions

```{r parameters}

convert_agregate<-function(df,index,subject,sep){
  l1=apply(X = df,MARGIN = 1,FUN = function(x) {
    m=as.data.frame( x = stringi::stri_split(str = x[subject],regex = sep),col.names = c("v1"))
    m["index"]<-x[index]
    return(m[c("index","v1")])
  })
  return(do.call(what = "rbind",args = l1) )
}
```

# Retrieve data from AnnotationHub

```{r annotation hub}

#gene_id_field options from Hub_columns:
#"ACCNUM", "ENSEMBL", "ENSEMBLPROT", "ENSEMBLTRANS", "ENTREZID", "REFSEQ", "SYMBOL", "UNIPROT"     
gene_id_field = "ENSEMBL"

cache = file.path(opt_outDir,'cache')
dir.create(cache, showWarnings = T)
ah  = AnnotationHub(cache = cache )  #takes some time
Hub = query(ah, c('OrgDb'))
species = unique(Hub$species)  #species list from the hub

dataset = species[(sapply(X = species,FUN = function(X) stringi::stri_startswith(fixed =  stringi::stri_trans_tolower(opt_Species),str =  stringi::stri_trans_tolower(X)    )))]
if (length(dataset) > 0) {
  print (paste("dataset: ", dataset))
  dataset = dataset[1]
  print('Found Species:')
  print(dataset)
  Hub = query(ah, c('OrgDb',dataset))
  Hub = Hub[[length(Hub$title)]]  #takes some time
  Hub_columns = columns(Hub)
  fields2use  = c('GENENAME','SYMBOL','GENETYPE', 'UNIPROT', 'PFAM', 'PATH') 
  print('Cloumns in DB:')
  print(Hub_columns)
  
  if (gene_id_field %in% columns(Hub)){
    
    Genes  = keys(Hub, keytype=gene_id_field) #retrieve list of all ensembl genes
    print ("No. of retrieved genes:")
    print (length(Genes))
    
    Annotation  = AnnotationDbi::select(Hub,                                       #Vered: this is BAD!!
                                        keys = as.character(Genes),
                                        columns=intersect(Hub_columns, fields2use),
                                        keytype=gene_id_field)
    print(dim(Annotation))

    if (('GOALL' %in% Hub_columns) & ('GO' %in% Hub_columns) ){
      GO_field2use = c('GOALL')
    }else{
      GO_field2use = c('GO')
    }
    
    GO_Annotation = AnnotationDbi::select(Hub,                                       
                                        keys = as.character(Genes),
                                        columns=intersect(Hub_columns, GO_field2use),
                                        keytype=gene_id_field)
    
    if ('GO' %in% Hub_columns) {
      colnames(GO_Annotation)['GO'    == colnames(GO_Annotation)] = 'go_id'
    }
    if ('GOALL' %in% Hub_columns) {
      colnames(GO_Annotation)['GOALL' == colnames(GO_Annotation)] = 'go_id'
    }
    
  }else{
    print('Could not find your Gene Type ID, These are the available options:')
    print(columns(Hub))
  }
} else {
  print ("length(dataset) is not > 0")
}
unlink(cache,recursive=TRUE)

```

# Write general annotation file

```{r print annotation file}

Annotation1 = Annotation
aggregate_by=Annotation1[gene_id_field]

Annotation1[gene_id_field]=NULL
Annotation1=aggregate.data.frame(x =Annotation1 ,
                                by = aggregate_by,
                                FUN =function(x) paste(unique(na.omit(x)),sep = "/",collapse = "/"))
rownames(Annotation1)=unlist(Annotation1[gene_id_field])
Annotation2<-apply(X =Annotation1,
                  MARGIN = c(1,2),
                  FUN =function(x) stringi::stri_replace_all(str = x,replacement = " ",regex = ",") )
Annotation2=as.data.frame(Annotation2)

write.table(Annotation2,
            file = file.path(opt_outDir,paste('Annotation','tab', sep = '.')),
            quote = F,
            row.names = F,
            sep = "\t")
```
# Write GO annotation file

```{r print GO info}

GO_Annotation1 = GO_Annotation
aggregate_by=GO_Annotation1[gene_id_field]

GO_Annotation1[gene_id_field]=NULL
GO_Annotation1=aggregate.data.frame(x =GO_Annotation1 ,
                                by = aggregate_by,
                                FUN =function(x) paste(unique(na.omit(x)),sep = "/",collapse = "/"))
rownames(GO_Annotation1)=unlist(GO_Annotation1[gene_id_field])
GO_Annotation2<-apply(X =GO_Annotation1,
                  MARGIN = c(1,2),
                  FUN =function(x) stringi::stri_replace_all(str = x,replacement = " ",regex = ",") )
GO_Annotation2=as.data.frame(GO_Annotation2)

write.table(GO_Annotation2,
            file = file.path(opt_outDir,paste('GO_Annotation','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")

```

# Write GO tables for enrichment analysis

```{r print GO info}

#the code below should be simplified by using the original GO_Annotation object before aggregation

GO2gene           = convert_agregate(GO_Annotation2,gene_id_field,"go_id","/")
GO2gene           = GO2gene[GO2gene$v1!='',]
GO2gene           = sapply(GO2gene,FUN = function(x) stringi::stri_replace_all(str = x,replacement = "",regex = " "))
GO2gene           = GO2gene[,c("v1","index")]
#convert GO indirect to direct GOs
GO2gene           = clusterProfiler::buildGOmap(GO2gene)
# annotate the GO to TERMs
Goterm            = merge.data.frame(x= clusterProfiler::go2term(GO2gene$GO), y=clusterProfiler::go2ont(GO2gene$GO) ,by='go_id')
Goterm            = Goterm[!duplicated.data.frame(Goterm),]
GO2name           = merge.data.frame(x = GO2gene,y = Goterm,by.y = "go_id",by.x ="GO" ,sort = FALSE)

GO2name_MF        = GO2name[GO2name$Ontology=="MF",c('GO','Term')]
GO2name_BP        = GO2name[GO2name$Ontology=="BP",c('GO','Term')]
GO2name_CC        = GO2name[GO2name$Ontology=="CC",c('GO','Term')]
GO2name_MF        = GO2name_MF[!duplicated.data.frame(GO2name_MF),]
GO2name_BP        = GO2name_BP[!duplicated.data.frame(GO2name_BP),]
GO2name_CC        = GO2name_CC[!duplicated.data.frame(GO2name_CC),]

GO2gene_MF        = GO2name[GO2name$Ontology=="MF",c('GO','Gene')]
GO2gene_BP        = GO2name[GO2name$Ontology=="BP",c('GO','Gene')]
GO2gene_CC        = GO2name[GO2name$Ontology=="CC",c('GO','Gene')]
GO2gene_MF        = GO2gene_MF[!duplicated.data.frame(GO2gene_MF),]
GO2gene_BP        = GO2gene_BP[!duplicated.data.frame(GO2gene_BP),]
GO2gene_CC        = GO2gene_CC[!duplicated.data.frame(GO2gene_CC),]

GO_flag           = TRUE
write.table(GO2gene_MF,
            file = file.path(opt_outDir,paste('GO2gene_MF','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")

write.table(GO2name_MF,
            file = file.path(opt_outDir,paste('GO2name_MF','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")


write.table(GO2gene_BP,
            file = file.path(opt_outDir,paste('GO2gene_BP','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")

write.table(GO2name_BP,
            file = file.path(opt_outDir,paste('GO2name_BP','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")

write.table(GO2gene_CC,
            file = file.path(opt_outDir,paste('GO2gene_CC','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")

write.table(GO2name_CC,
            file = file.path(opt_outDir,paste('GO2name_CC','tab', sep = '.')) ,
            quote = F,
            row.names = F,
            sep = "\t")
```